### PR TITLE
Adding support for editable namespace packages

### LINKED ISSUE #28: Editable install fails when an extension depending on a DSO is located in a namespace package
I have a minimal working example here: https://gitlab.com/Thf772/setuptools-dso-multi-namespace-test

When a namespace package is installed in editable mode, trying to install an Extension depending on a DSO located in the same namespace package will fail, whether that install is editable or not, on both Linux and Windows.

### Steps to reproduce:
 - Create a first Python project with only one python file, `nsp/core/__init__.py`
 - Do not create an `nsp.__init__.py` file
 - Create a second Python project with:
     - `nsp/dso/thedso.c`
     - `nsp/dso/theext.pyx`
     - `nsp/dso/__init__.py`
 - Configure the second project to build a DSO using `thedso.c`, and an extension that depends on this DSO using `theext.pyx`
 - Install the first project in a virtual environment in editable mode
 - Install the second project in the same virtual environment in either normal or editable mode

My MWE above uses different names.

### Expected result
The second install succeeds

### Actual result
An error occurs while building the second project:

```
  × Building editable for test-dso-nsp-dso (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [159 lines of output]
      running editable_wheel
      creating /tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info
      writing /tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file '/tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso-0.0.0.dist-info'
      Original Wheel Tag: cp311, cp311, linux_x86_64
      creating /tmp/pip-wheel-4259yequ/.tmp-9qjk9ar7/test_dso_nsp_dso-0.0.0.dist-info/WHEEL
      Original Wheel Tag: cp311, cp311, linux_x86_64
      running build_py
      running build_dso
      Building DSOs
      Patch _fix_compile_args() to avoid modification to compiler.include_dirs
      building 'testnsp.testdso.thedso' DSO as /tmp/tmptr6erjpr.build-lib/testnsp/testdso/libthedso.so
      effective NUM_JOBS=2
      _patch_fix_compile_args include_dirs=[]
      creating /tmp/tmpqx2ffds9.build-temp/testnsp
      creating /tmp/tmpqx2ffds9.build-temp/testnsp/testdso
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -c testnsp/testdso/libtest.c -o /tmp/tmpqx2ffds9.build-temp/testnsp/testdso/libtest.o
      _patch_fix_compile_args include_dirs=[]
      creating /tmp/tmptr6erjpr.build-lib/testnsp
      creating /tmp/tmptr6erjpr.build-lib/testnsp/testdso
      gcc -shared /tmp/tmpqx2ffds9.build-temp/testnsp/testdso/libtest.o -o /tmp/tmptr6erjpr.build-lib/testnsp/testdso/libthedso.so
      copying /tmp/tmptr6erjpr.build-lib/testnsp/testdso/libthedso.so -> testnsp/testdso
      creating info module for testnsp.testdso.thedso at /tmp/tmptr6erjpr.build-lib/testnsp/testdso/thedso_dsoinfo.py
      copying /tmp/tmptr6erjpr.build-lib/testnsp/testdso/thedso_dsoinfo.py -> testnsp/testdso
      running build_ext
      Traceback (most recent call last):
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools_dso/dsocmd.py", line 577, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools_dso/dsocmd.py", line 588, in build_extension
          self.dso2lib_pre(ext)
        File "/tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools_dso/dsocmd.py", line 222, in dso2lib_pre
          dsobase = os.path.dirname(import_module(parts[0]).__file__)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen posixpath>", line 152, in dirname
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      /tmp/pip-build-env-wqunbmez/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
```

### What I *think* happens
Looking at the source, this exception is thrown while Setuptools-DSO is building the possible locations for an existing DSO. It looks for the init file of the root package (`nsp` in the reproduction instructions, `testnsp` in my MWE), but since this is a namespace package, this file does not exist. So while the import works (no `ImportError` so the `except` clause is not triggered), `__file__` contains `None` and causes a `TypeError` when fed to `os.path.dirname`.

To solve it, I think it should be possible to set up a `while` (or even better, `for`) loop to look first at `parts[0:1]`, see if it's a real package (`__file__ is not None`), and if it's not, try again with `parts[0:2]` and so on. Since I'm in this exact situation in a project of mine, I might make a PR for this, if no one does it before.

### PR DESCRIPTION
**Pull request by Thf772**
Namespace packages installed as editable have no `__file__` which causes a crash when installing Extensions and DSOs that depend on other DSOs located insde them. Now instead of only looking at the root package to find a DSO, we look for the first package with a non-None `__file__`.

Fixes #28

### CODE REVIEW

**Comment by mdavidsaver** [comment]
@Thf772 Are you able to enable github actions runs in your personal repository?  I don't want my having to (re)approve GHA runs to be an impediment to you getting feedback.

**Comment by Thf772** [comment]
I've tried setting it up, but apparently I can't run it manually so I don't know if it'll work

**Comment by Thf772** [comment]
Thanks, apparently workflows work in my fork so it should not be as important. Thank you for the help so far. Also apparently you were right about ` __file__` not existing on namespace packages in older Pythons, the Python 3.6 test failed because of that.

**Comment by Thf772** [comment]
Alright, finally I managed to fix the workflow completely. There was another weird bug and I had to dig far too deep and too greedily into Setuptools code to understand...

Basically: when building in editable mode, `build_dso` is called as a subcommand of `build_ext`, but build_ext doesn't pass the `inplace` flag automatically. This means the DSO doesn't get copied into the package directory, and it causes a "File not found" when trying to load it. I don't know why it only causes a crash on MacOS, but at least the problem should be solved.

**Comment by mdavidsaver** [comment]
Partially squashed and merged as of 751e45c28c2c4c405f5a4ac26ec4117a103a6e39.  I also made some additional changes in 9db427e8c00b8b2a3afbf2933c775c051a374e93 which are mostly to add comments, but also include some reorganizing.

**Comment by mdavidsaver** [comment]
> ... I had to dig far too deep and too greedily into Setuptools code to understand...

An masterful summary of my entire experience with setuptools!

**Pull request closed without merging**
