### PR TITLE
Fix support for develop install (pip install -e)

### PR DESCRIPTION
**Pull request by navytux**
Please see details in the last [patch](https://github.com/mdavidsaver/setuptools_dso/commit/a5ff0fa4687d10665bf2b88246c438ad27e76e10).

### CODE REVIEW

**Comment by navytux** [comment]
( CI: Travis is all [green](https://travis-ci.org/github/mdavidsaver/setuptools_dso/builds/686931129) but somehow this status is not propagated to this pull request on github )

**Comment by mdavidsaver** [comment]
I hadn't paid much attention to editable installs before.  I can see this being useful when both `DSO` and `Extension` are in the same package.  Your change looks reasonable, so no problem with merging.

**Comment by navytux** [comment]
Thanks

**Comment by mdavidsaver** [comment]
Released in [1.7](https://pypi.org/project/setuptools-dso/1.7/)

**Comment by navytux** [comment]
@mdavidsaver, thanks, very convenient. P.S. https://lab.nexedi.com/nexedi/pygolang/commit/34b9c0cf

**Pull request merged**
